version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "%(asctime)s %(name)s %(levelname)s %(module)s %(funcName)s %(lineno)d %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    class: "pythonjsonlogger.jsonlogger.JsonFormatter"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /opt/archie/data/logs/archie.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /opt/archie/data/logs/archie_errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  voice_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /opt/archie/data/logs/voice.log
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8
  
  memory_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /opt/archie/data/logs/memory.log
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8
  
  automation_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /opt/archie/data/logs/automation.log
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8

loggers:
  archie_core:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false
  
  archie_core.voice:
    level: INFO
    handlers: [console, voice_file]
    propagate: false
  
  archie_core.memory:
    level: INFO
    handlers: [console, memory_file]
    propagate: false
  
  archie_core.automation:
    level: INFO
    handlers: [console, automation_file]
    propagate: false
  
  homeassistant:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  n8n:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  whisper:
    level: WARNING
    handlers: [console, voice_file]
    propagate: false
  
  transformers:
    level: WARNING
    handlers: [console, file]
    propagate: false
  
  chromadb:
    level: INFO
    handlers: [console, memory_file]
    propagate: false
  
  urllib3:
    level: WARNING
    handlers: [console]
    propagate: false
  
  requests:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console, file]